language: python
python:
  - "2.7"
env:
  global:
    - DJANGO_SETTINGS_MODULE=ladder.settings
    - DATABASE_URL='sqlite:///sqlite_database'
    - secure: "bsJ0aTQVId4zdxUC0Cn5LCodvrveG61IfFEqJtCvcTXEg0+X3Gqya/Zsjyg/VMEgtGhhLSSVsE/+1CE4Cdum1RoxZif/tSMhomSjAL+GTIECiBV1YnKjdEkaTkICmhMtoGGZCPY/cVGPlw8oP1xTiUnPpiAwhrMsqWaCbvoPiDU="
    - secure: "KbuJN97KTNn2ufcIGR4dUnYgsy2jOgT8sBu29nM2MokZnHAelFjcW7Zso6Vdsko3YHqy8tSsNjqb+/0gml2VIStFLkT7762im+DWL2e2wT5yBuGHZ3FvpZVRVnoCYALH/cGFrAWvrNid/CjcoOi50M7NlKOdD1vD/Ym+WFt6yiY="
    - TWILIO_PHONE_NUMBER='+15005550006'
install: pip install -r requirements.txt
script: "python manage.py test"
